baseURL = 'https://iguessthatworks.com/'
# title = 'Working'
# canonifyurls = true
copyright = "Jeff Mayeur"
enableRobotsTXT = true
paginate = 10
theme = "hugo-clarity"


[params]
  title_short = "It Works"
  description = "Musings by Jeff Mayeur on Learning and Working in Technology"
  author = "Jeff Mayeur"
  keywords =['Technology', 'Learning', 'Play']
  numberOfTagsShown = 15
  codeMaxLines = 7
  enableSearch = true
  blogDir = "posts"
  fallBackOgImage = "images/screenshot.png"
  authorDescription = "Jeff Mayeur is a software, data and operations engineer and engineering leader, building web and data systems since the turn of the century."
  authorImage = "images/about/jeff.png"
  authorSameAs = [
    "https://www.linkedin.com/in/jeff-mayeur/",
    "https://github.com/jmayeur",
    "https://jmayeur.dev"
  ]

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'images'
  target = 'static/images'
