baseURL = 'https://iguessthatworks.com/'
languageCode = 'en-us'
title = 'Working!'
  
paginate = 10
theme = "hugo-clarity"

copyright = "Jeff Mayeur"

enableRobotsTXT = true

DefaultContentLanguage = "en"
# [languages]

# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[module.mounts]]
source = 'static'
target = 'static'
[[module.mounts]]
source = 'images'
target = 'static/images'

codeMaxLines = 7

[params.social]
linkedin = "https://www.linkedin.com/in/jeff-mayeur/"