baseURL = 'https://iguessthatworks.com/'
languageCode = 'en-us'
title = 'Working!'
  
paginate = 10
theme = "hugo-clarity"

copyright = "Jeff Mayeur"

DefaultContentLanguage = "en"
# [languages]

# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]